<?php
/**
 * Sample CCTV requests for testing.
 * Run: php api/seed_cctv_requests_sample.php
 */

require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/cctv_requests_schema.php';

if (!$pdo instanceof PDO) {
    fwrite(STDERR, "Database connection unavailable.\n");
    exit(1);
}

ensureCctvRequestsTable($pdo);

$today = date('Y-m-d');
$year = date('Y');

$samples = [
    [
        'request_id' => "CCTV-RFQ-{$year}-SAMPLE-001",
        'source' => 'sample_seed',
        'source_reference_id' => 'SEED-001',
        'requesting_agency' => 'Quezon City Police District',
        'contact_person' => 'PO2 Ana Reyes',
        'contact_position' => 'Investigator',
        'contact_number' => '09171234567',
        'contact_email' => 'ana.reyes@qcpd.gov.ph',
        'office_unit' => 'Station 5 Investigation',
        'case_reference' => 'INV-2026-SAMPLE-01',
        'related_complaint_id' => null,
        'purpose' => 'Investigation',
        'purpose_details' => 'Footage needed for ongoing investigation of suspicious activity near the barangay hall.',
        'legal_basis' => 'Law enforcement request',
        'incident_location' => 'Susano Road, Barangay San Agustin, Quezon City',
        'camera_id' => 'CAM-001',
        'location_description' => 'Main Entrance Camera — Susano Road',
        'incident_date' => $today,
        'footage_start_time' => '16:30:00',
        'footage_end_time' => '17:00:00',
        'incident_type' => 'Suspicious activity',
        'incident_description' => 'Persons loitering near the main entrance after hours.',
        'delivery_method' => 'secure_download',
        'supporting_document' => null,
        'status' => 'Pending',
        'review_notes' => null,
        'rejection_reason' => null,
        'approved_camera_id' => null,
        'actual_footage_start' => null,
        'actual_footage_end' => null,
        'fulfillment_notes' => null,
        'reviewed_by' => null,
        'fulfilled_at' => null,
        'submitted_at' => $today . ' 09:15:00',
    ],
    [
        'request_id' => "CCTV-RFQ-{$year}-SAMPLE-002",
        'source' => 'sample_seed',
        'source_reference_id' => 'SEED-002',
        'requesting_agency' => 'Barangay San Agustin Hall',
        'contact_person' => 'Kagawad Miguel Santos',
        'contact_position' => 'Peace and Order Committee',
        'contact_number' => '09189876543',
        'contact_email' => 'm.santos@barangay-sanagustin.gov.ph',
        'office_unit' => 'BPSO Desk',
        'case_reference' => 'BRGY-2026-SAMPLE-02',
        'related_complaint_id' => null,
        'purpose' => 'Incident verification',
        'purpose_details' => 'Verify reported pedestrian incident near the barangay gate.',
        'legal_basis' => 'Barangay request',
        'incident_location' => 'Main entrance area, Brgy. San Agustin',
        'camera_id' => 'CAM-001',
        'location_description' => 'Main Entrance Camera',
        'incident_date' => date('Y-m-d', strtotime('-1 day')),
        'footage_start_time' => '15:40:00',
        'footage_end_time' => '16:20:00',
        'incident_type' => 'Traffic / pedestrian incident',
        'incident_description' => 'Reported near-miss involving a motorcycle and pedestrian.',
        'delivery_method' => 'secure_download',
        'supporting_document' => null,
        'status' => 'Under Review',
        'review_notes' => 'Camera coverage confirmed. Reviewing available segments.',
        'rejection_reason' => null,
        'approved_camera_id' => 'CAM-001',
        'actual_footage_start' => '15:40:00',
        'actual_footage_end' => '16:20:00',
        'fulfillment_notes' => null,
        'reviewed_by' => 'BPSO Admin',
        'fulfilled_at' => null,
        'submitted_at' => date('Y-m-d', strtotime('-1 day')) . ' 14:30:00',
    ],
    [
        'request_id' => "CCTV-RFQ-{$year}-SAMPLE-003",
        'source' => 'sample_seed',
        'source_reference_id' => 'SEED-003',
        'requesting_agency' => 'Quezon City Police District',
        'contact_person' => 'SPO1 Carla Mendoza',
        'contact_position' => 'Desk Officer',
        'contact_number' => '09175551234',
        'contact_email' => 'c.mendoza@qcpd.gov.ph',
        'office_unit' => 'Station 5 Desk',
        'case_reference' => 'INV-2026-SAMPLE-03',
        'related_complaint_id' => null,
        'purpose' => 'Evidence gathering',
        'purpose_details' => 'Requesting evening footage for a reported snatching incident.',
        'legal_basis' => 'Law enforcement request',
        'incident_location' => 'Ambrocia Street, Barangay San Agustin',
        'camera_id' => 'CAM-002',
        'location_description' => 'Ambrocia Street corner camera',
        'incident_date' => date('Y-m-d', strtotime('-3 days')),
        'footage_start_time' => '19:00:00',
        'footage_end_time' => '20:30:00',
        'incident_type' => 'Theft / snatching',
        'incident_description' => 'Complainant reported bag snatching near Ambrocia Street around 7:45 PM.',
        'delivery_method' => 'secure_download',
        'supporting_document' => null,
        'status' => 'Approved',
        'review_notes' => 'Approved. Footage window covers the reported time.',
        'rejection_reason' => null,
        'approved_camera_id' => 'CAM-002',
        'actual_footage_start' => '19:00:00',
        'actual_footage_end' => '20:30:00',
        'fulfillment_notes' => null,
        'reviewed_by' => 'BPSO Admin',
        'fulfilled_at' => null,
        'submitted_at' => date('Y-m-d', strtotime('-3 days')) . ' 21:10:00',
    ],
    [
        'request_id' => "CCTV-RFQ-{$year}-SAMPLE-004",
        'source' => 'sample_seed',
        'source_reference_id' => 'SEED-004',
        'requesting_agency' => 'Barangay San Agustin Hall',
        'contact_person' => 'Secretary Liza Navarro',
        'contact_position' => 'Barangay Secretary',
        'contact_number' => '09182223344',
        'contact_email' => 'l.navarro@barangay-sanagustin.gov.ph',
        'office_unit' => 'Barangay Secretariat',
        'case_reference' => 'BRGY-2026-SAMPLE-04',
        'related_complaint_id' => null,
        'purpose' => 'Complaint support',
        'purpose_details' => 'Support documentation for a noise disturbance complaint.',
        'legal_basis' => 'Barangay request',
        'incident_location' => 'Clemente Street, Barangay San Agustin',
        'camera_id' => 'CAM-003',
        'location_description' => 'Clemente Street residential camera',
        'incident_date' => date('Y-m-d', strtotime('-5 days')),
        'footage_start_time' => '22:00:00',
        'footage_end_time' => '23:30:00',
        'incident_type' => 'Disturbance',
        'incident_description' => 'Residents reported loud gathering and possible altercation late evening.',
        'delivery_method' => 'secure_download',
        'supporting_document' => null,
        'status' => 'Fulfilled',
        'review_notes' => 'Footage clipped and released via secure download.',
        'rejection_reason' => null,
        'approved_camera_id' => 'CAM-003',
        'actual_footage_start' => '22:00:00',
        'actual_footage_end' => '23:30:00',
        'fulfillment_notes' => 'Secure link delivered to requesting office.',
        'reviewed_by' => 'BPSO Admin',
        'fulfilled_at' => date('Y-m-d', strtotime('-4 days')) . ' 10:00:00',
        'submitted_at' => date('Y-m-d', strtotime('-5 days')) . ' 08:45:00',
    ],
    [
        'request_id' => "CCTV-RFQ-{$year}-SAMPLE-005",
        'source' => 'sample_seed',
        'source_reference_id' => 'SEED-005',
        'requesting_agency' => 'Quezon City Police District',
        'contact_person' => 'PO3 David Cruz',
        'contact_position' => 'Investigator',
        'contact_number' => '09176667788',
        'contact_email' => 'd.cruz@qcpd.gov.ph',
        'office_unit' => 'Station 5 Investigation',
        'case_reference' => 'INV-2026-SAMPLE-05',
        'related_complaint_id' => null,
        'purpose' => 'Investigation',
        'purpose_details' => 'Morning footage requested for a hit-and-run follow-up.',
        'legal_basis' => 'Law enforcement request',
        'incident_location' => 'Quezon Avenue Extension, Barangay San Agustin',
        'camera_id' => 'CAM-001',
        'location_description' => 'Roadside camera facing Quezon Avenue Extension',
        'incident_date' => date('Y-m-d', strtotime('-7 days')),
        'footage_start_time' => '06:30:00',
        'footage_end_time' => '08:00:00',
        'incident_type' => 'Hit and run',
        'incident_description' => 'Vehicle reportedly fled after colliding with a parked motorcycle.',
        'delivery_method' => 'secure_download',
        'supporting_document' => null,
        'status' => 'Rejected',
        'review_notes' => null,
        'rejection_reason' => 'Requested camera was offline during the specified time window.',
        'approved_camera_id' => null,
        'actual_footage_start' => null,
        'actual_footage_end' => null,
        'fulfillment_notes' => null,
        'reviewed_by' => 'BPSO Admin',
        'fulfilled_at' => null,
        'submitted_at' => date('Y-m-d', strtotime('-7 days')) . ' 11:20:00',
    ],
];

$inserted = 0;
$skipped = 0;

foreach ($samples as $row) {
    $check = $pdo->prepare('SELECT id FROM cctv_requests WHERE request_id = :request_id LIMIT 1');
    $check->execute([':request_id' => $row['request_id']]);
    if ($check->fetch()) {
        echo "Skip existing: {$row['request_id']}\n";
        $skipped++;
        continue;
    }

    $stmt = $pdo->prepare('INSERT INTO cctv_requests (
        request_id, source, source_reference_id, requesting_agency, contact_person, contact_position,
        contact_number, contact_email, office_unit, case_reference, related_complaint_id,
        purpose, purpose_details, legal_basis, incident_location, camera_id, location_description,
        incident_date, footage_start_time, footage_end_time, incident_type, incident_description,
        delivery_method, supporting_document, status, review_notes, rejection_reason,
        approved_camera_id, actual_footage_start, actual_footage_end, fulfillment_notes,
        reviewed_by, fulfilled_at, submitted_at
    ) VALUES (
        :request_id, :source, :source_reference_id, :requesting_agency, :contact_person, :contact_position,
        :contact_number, :contact_email, :office_unit, :case_reference, :related_complaint_id,
        :purpose, :purpose_details, :legal_basis, :incident_location, :camera_id, :location_description,
        :incident_date, :footage_start_time, :footage_end_time, :incident_type, :incident_description,
        :delivery_method, :supporting_document, :status, :review_notes, :rejection_reason,
        :approved_camera_id, :actual_footage_start, :actual_footage_end, :fulfillment_notes,
        :reviewed_by, :fulfilled_at, :submitted_at
    )');

    $stmt->execute([
        ':request_id' => $row['request_id'],
        ':source' => $row['source'],
        ':source_reference_id' => $row['source_reference_id'],
        ':requesting_agency' => $row['requesting_agency'],
        ':contact_person' => $row['contact_person'],
        ':contact_position' => $row['contact_position'],
        ':contact_number' => $row['contact_number'],
        ':contact_email' => $row['contact_email'],
        ':office_unit' => $row['office_unit'],
        ':case_reference' => $row['case_reference'],
        ':related_complaint_id' => $row['related_complaint_id'],
        ':purpose' => $row['purpose'],
        ':purpose_details' => $row['purpose_details'],
        ':legal_basis' => $row['legal_basis'],
        ':incident_location' => $row['incident_location'],
        ':camera_id' => $row['camera_id'],
        ':location_description' => $row['location_description'],
        ':incident_date' => $row['incident_date'],
        ':footage_start_time' => $row['footage_start_time'],
        ':footage_end_time' => $row['footage_end_time'],
        ':incident_type' => $row['incident_type'],
        ':incident_description' => $row['incident_description'],
        ':delivery_method' => $row['delivery_method'],
        ':supporting_document' => $row['supporting_document'],
        ':status' => $row['status'],
        ':review_notes' => $row['review_notes'],
        ':rejection_reason' => $row['rejection_reason'],
        ':approved_camera_id' => $row['approved_camera_id'],
        ':actual_footage_start' => $row['actual_footage_start'],
        ':actual_footage_end' => $row['actual_footage_end'],
        ':fulfillment_notes' => $row['fulfillment_notes'],
        ':reviewed_by' => $row['reviewed_by'],
        ':fulfilled_at' => $row['fulfilled_at'],
        ':submitted_at' => $row['submitted_at'],
    ]);

    echo "Inserted: {$row['request_id']} ({$row['status']})\n";
    $inserted++;
}

echo "\nDone. Inserted {$inserted}, skipped {$skipped}.\n";
